server:
  port: 9000
spring:
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:7777/burgerbox
    username: user_burgerbox
    password: pass_burgerbox

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
mp:
  accessToken: APP_USR-7208984657366749-030815-1f01b22a4239823292fb85e60d2dd95e-239027380