version: '3.9'
services:
  db:
    image: postgres
    restart: always 
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../data/burgerbox.db:/var/lib/postgresql/data
      - ../src/main/resources/db/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '7777:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080